# Generated by Django 3.0.4 on 2022-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='День')),
                ('hour', models.FloatField(verbose_name='Час')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Работник')),
                ('an_hour_a_day', models.ManyToManyField(to='landing_app.WorkingTime', verbose_name='Час в день')),
            ],
        ),
    ]
