# Generated by Django 3.0.4 on 2022-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0002_auto_20220308_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='date',
            field=models.DateField(verbose_name='День'),
        ),
    ]
